# Generated by Django 3.0 on 2021-03-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210326_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
